import Navbar from "../../components/Navbar";

export default function Evidence() {
  return (
    <main className="min-h-screen bg-[#070b14] text-white px-6 py-12">
      <div className="max-w-5xl mx-auto">

        <p className="text-cyan-400 tracking-[0.3em] text-sm">
          SYNAPSELAB / EVIDENCE
        </p>

        <h1 className="text-4xl md:text-5xl font-bold mt-4">
          Scientific Evidence
        </h1>

        <p className="text-gray-400 mt-6 max-w-3xl leading-relaxed">
          SynapseLab is inspired by established research on
          synaptic plasticity, learning, and memory. The sources
          below support the biological motivation for the model,
          while the numerical results produced by SynapseLab are
          generated by our own simplified simulation.
        </p>

        {/* Evidence 01 */}

        <section className="mt-10 bg-white/5 border border-white/10 rounded-2xl p-6">

          <p className="text-cyan-400 text-sm font-semibold">
            EVIDENCE 01
          </p>

          <h2 className="text-2xl font-semibold mt-2">
            Synaptic plasticity and memory
          </h2>

          <p className="text-gray-400 mt-4 leading-relaxed">
            Research has extensively investigated whether
            activity-dependent changes in synapses contribute
            to memory formation and storage. Work involving the
            hippocampus provides an important connection between
            synaptic plasticity and memory.
          </p>

          <div className="mt-5 border-l-2 border-cyan-400 pl-4">
            <p className="font-semibold">
              Neves, G., Cooke, S. F., & Bliss, T. V. P. (2008)
            </p>

            <p className="text-gray-500 text-sm mt-1">
              Synaptic plasticity, memory and the hippocampus:
              a neural network approach to causality.
            </p>

            <p className="text-gray-500 text-sm mt-1">
              Nature Reviews Neuroscience, 9, 65–75.
            </p>
          </div>

        </section>

        {/* Evidence 02 */}

        <section className="mt-6 bg-white/5 border border-white/10 rounded-2xl p-6">

          <p className="text-cyan-400 text-sm font-semibold">
            EVIDENCE 02
          </p>

          <h2 className="text-2xl font-semibold mt-2">
            Synaptic plasticity as a computational mechanism
          </h2>

          <p className="text-gray-400 mt-4 leading-relaxed">
            Synaptic plasticity is commonly described as
            activity-dependent changes in neuronal connection
            strength. Computational models use changes in
            connection weights to represent learning.
          </p>

          <div className="mt-5 border-l-2 border-cyan-400 pl-4">
            <p className="font-semibold">
              Magee, J. C., & Grienberger, C. (2020)
            </p>

            <p className="text-gray-500 text-sm mt-1">
              Synaptic Plasticity Forms and Functions.
            </p>

            <p className="text-gray-500 text-sm mt-1">
              Annual Review of Neuroscience, 43, 95–117.
            </p>
          </div>

        </section>

        {/* Evidence 03 */}

        <section className="mt-6 bg-white/5 border border-white/10 rounded-2xl p-6">

          <p className="text-cyan-400 text-sm font-semibold">
            EVIDENCE 03
          </p>

          <h2 className="text-2xl font-semibold mt-2">
            Important scientific limitation
          </h2>

          <p className="text-gray-400 mt-4 leading-relaxed">
            Although synaptic plasticity has strong support as
            a mechanism involved in learning and memory, research
            does not establish that all memories are stored
            exclusively at synapses. Other cellular and network
            mechanisms may also contribute.
          </p>

          <div className="mt-5 border-l-2 border-cyan-400 pl-4">
            <p className="font-semibold">
              Abraham, W. C., Jones, O. D., & Glanzman, D. L. (2019)
            </p>

            <p className="text-gray-500 text-sm mt-1">
              Is plasticity of synapses the mechanism of
              long-term memory storage?
            </p>

            <p className="text-gray-500 text-sm mt-1">
              npj Science of Learning, 4, Article 9.
            </p>
          </div>

        </section>

        {/* Recent evidence */}

        <section className="mt-6 bg-white/5 border border-white/10 rounded-2xl p-6">

          <p className="text-cyan-400 text-sm font-semibold">
            RECENT RESEARCH
          </p>

          <h2 className="text-2xl font-semibold mt-2">
            Behavioral-timescale plasticity
          </h2>

          <p className="text-gray-400 mt-4 leading-relaxed">
            Recent research has identified forms of synaptic
            plasticity that operate over behavioral timescales
            and may contribute to experience-based learning
            and memory. This reinforces the broader idea that
            synaptic changes can occur on timescales relevant
            to behavior.
          </p>

          <div className="mt-5 border-l-2 border-cyan-400 pl-4">
            <p className="font-semibold">
              Magee, J. C. (2026)
            </p>

            <p className="text-gray-500 text-sm mt-1">
              Behavioral timescale synaptic plasticity:
              properties, elements and functions.
            </p>

            <p className="text-gray-500 text-sm mt-1">
              Nature Neuroscience, 29, 520–534.
            </p>
          </div>

        </section>

        {/* Model vs evidence */}

        <section className="mt-10 border border-cyan-400/20 rounded-2xl p-6">

          <h2 className="text-xl font-semibold">
            Biology vs. Simulation
          </h2>

          <div className="grid md:grid-cols-2 gap-5 mt-6">

            <div className="bg-white/5 rounded-xl p-5">

              <p className="text-cyan-400 text-sm font-semibold">
                PUBLISHED EVIDENCE
              </p>

              <p className="text-gray-400 mt-3 leading-relaxed">
                Scientific literature supports the importance
                of synaptic plasticity in learning and memory,
                while also showing that the biological picture
                is more complex than a single mechanism.
              </p>

            </div>

            <div className="bg-white/5 rounded-xl p-5">

              <p className="text-cyan-400 text-sm font-semibold">
                SYNAPSELAB RESULT
              </p>

              <p className="text-gray-400 mt-3 leading-relaxed">
                Our model numerically demonstrates how changing
                connection weights can create a temporary memory
                state and how subsequent learning can reduce
                the strength of that state.
              </p>

            </div>

          </div>

        </section>

        {/* Final note */}

        <section className="mt-6 bg-white/5 border border-white/10 rounded-2xl p-6">

          <h2 className="text-xl font-semibold">
            Scientific interpretation
          </h2>

          <p className="text-gray-400 mt-3 leading-relaxed">
            The literature provides the biological motivation.
            SynapseLab does not claim to reproduce biological
            memory. Its 40% interference result is a property
            of our simplified computational model, not a
            measurement of human memory.
          </p>

        </section>

      </div>
    </main>
  );
}